import {
  Receipt,
  CheckCircle2,
  Minus,
  Hourglass,
  Undo2,
  CreditCard,
  TrendingUp,
  AlertTriangle,
} from "lucide-react";
import { COLORS } from "./colors";

export const DEFAULT_ADMIN_ROLES = [
  { id: 1, name: "Accounts" },
  { id: 2, name: "Admin Manager" },
];

export const DEFAULT_BRANCH_ROLES = [
  { id: 1, name: "Manager" },
  { id: 2, name: "Assistant Manager" },
  { id: 3, name: "MD.NAZRUL Islam" },
  { id: 4, name: "Branch Mangar 1" },
];

export const DEFAULT_SHOP_BRANCHES = [
  {
    id: 1,
    name: "My Shop",
    address: "Shop-1205, Lift-0 Saha Ali Plaza, Mirpur-10, Dhaka-1216",
    type: "shop",
  },
  { id: 2, name: "My Business", address: "Dhaka", type: "shop" },
  {
    id: 3,
    name: "Godown Gulshan",
    address: "Arong Building, 10th Floor, Pallabi, Mirpur-12, Dhaka",
    type: "godown",
  },
  {
    id: 4,
    name: "Godown Kadamtali",
    address: "Komlanesa Steel Market, Chowrasta, Gazipur.",
    type: "godown",
  },
  { id: 5, name: "Godwon Badda", address: "lusto est magnam et", type: "godown" },
  { id: 6, name: "rana", address: "mirpur", type: "shop" },
  { id: 7, name: "rana2", address: "mirpur", type: "shop" },
];

export const KPI_DATA = [
  {
    label: "Total Sales",
    value: "14,240.00",
    trend: "+12.4%",
    up: true,
    icon: Receipt,
    fg: COLORS.magenta,
    bg: COLORS.magentaTint,
  },
  {
    label: "Instant Paid",
    value: "14,240.00",
    trend: "+8.1%",
    up: true,
    icon: CheckCircle2,
    fg: COLORS.forest,
    bg: COLORS.forestTint,
  },
  {
    label: "Total Expense",
    value: "2,200.00",
    trend: "-3.2%",
    up: false,
    icon: Minus,
    fg: COLORS.vermillion,
    bg: COLORS.vermillionTint,
  },
  {
    label: "Due Paid",
    value: "600.00",
    trend: "-1.5%",
    up: false,
    icon: Hourglass,
    fg: COLORS.purple,
    bg: COLORS.purpleTint,
  },
  {
    label: "Total Return",
    value: "1,500.00",
    trend: "+5.0%",
    up: true,
    icon: Undo2,
    fg: COLORS.rust,
    bg: COLORS.rustTint,
  },
  {
    label: "Total Payment",
    value: "7,000.00",
    trend: "+9.7%",
    up: true,
    icon: CreditCard,
    fg: COLORS.marigold,
    bg: COLORS.marigoldTint,
  },
  {
    label: "Stock Alert Qty",
    value: "03",
    trend: "3 items",
    up: false,
    icon: AlertTriangle,
    fg: COLORS.peacock,
    bg: COLORS.peacockTint,
    noCurrency: true,
  },
  {
    label: "Total Income",
    value: "1,200.00",
    trend: "+4.4%",
    up: true,
    icon: TrendingUp,
    fg: COLORS.forestDark,
    bg: COLORS.forestTint,
  },
];

export const SALES_TREND = [
  { day: "শনি", sales: 9200 },
  { day: "রবি", sales: 10800 },
  { day: "সোম", sales: 8600 },
  { day: "মঙ্গল", sales: 12400 },
  { day: "বুধ", sales: 11300 },
  { day: "বৃহঃ", sales: 13950 },
  { day: "শুক্র", sales: 14240 },
];

export const STOCK_ALERTS = [
  { name: "Cotton Panjabi — L", branch: "Mirpur-2", qty: "2 pcs" },
  { name: "Denim Jeans — 32", branch: "Uttara", qty: "4 pcs" },
  { name: "Kids T-Shirt — M", branch: "Mirpur-2", qty: "1 pc" },
];

export const TRANSACTIONS = [
  {
    inv: "#INV-1042",
    name: "Rafiq Hasan",
    initials: "RH",
    branch: "Mirpur-2",
    status: "Paid",
    amount: "3,200.00",
  },
  {
    inv: "#INV-1041",
    name: "Nadia Akter",
    initials: "NA",
    branch: "Uttara",
    status: "Due",
    amount: "1,850.00",
  },
  {
    inv: "#INV-1040",
    name: "Shakil Islam",
    initials: "SI",
    branch: "Mirpur-2",
    status: "Paid",
    amount: "5,400.00",
  },
  {
    inv: "#INV-1039",
    name: "Mahin Jaman",
    initials: "MJ",
    branch: "Dhanmondi",
    status: "Due",
    amount: "900.00",
  },
];

export const DEFAULT_BRANDS = [
  { id: 1, name: "Aarong" },
  { id: 2, name: "Yellow" },
  { id: 3, name: "Ecstasy" },
  { id: 4, name: "Sailor" },
  { id: 5, name: "Richman" },
];

export const DEFAULT_CATEGORIES = [
  { id: 1, name: "Panjabi" },
  { id: 2, name: "Shirt" },
  { id: 3, name: "Jeans" },
  { id: 4, name: "T-Shirt" },
  { id: 5, name: "Kids Wear" },
  { id: 6, name: "Saree" },
];

export const DEFAULT_UNIT_TYPES = [
  { id: 1, name: "Pieces", short: "Pcs" },
  { id: 2, name: "Kilogram", short: "Kg" },
  { id: 3, name: "Dozen", short: "Dz" },
  { id: 4, name: "Box", short: "Box" },
];

export const DEFAULT_VARIATIONS = [
  { id: 1, name: "Size", values: ["S", "M", "L", "XL", "XXL"] },
  { id: 2, name: "Color", values: ["Red", "Blue", "Black", "White"] },
];

export const DEFAULT_ALL_PRODUCTS = [
  {
    id: 1,
    name: "Cotton Panjabi — L",
    category: "Panjabi",
    brand: "Aarong",
    purchase: "850.00",
    selling: "1,450.00",
    stock: 24,
  },
  {
    id: 2,
    name: "Denim Jeans — 32",
    category: "Jeans",
    brand: "Yellow",
    purchase: "1,100.00",
    selling: "1,890.00",
    stock: 4,
  },
  {
    id: 3,
    name: "Kids T-Shirt — M",
    category: "Kids Wear",
    brand: "Ecstasy",
    purchase: "220.00",
    selling: "390.00",
    stock: 1,
  },
  {
    id: 4,
    name: "Formal Shirt — XL",
    category: "Shirt",
    brand: "Sailor",
    purchase: "650.00",
    selling: "1,150.00",
    stock: 32,
  },
  {
    id: 5,
    name: "Printed Saree",
    category: "Saree",
    brand: "Richman",
    purchase: "1,800.00",
    selling: "2,950.00",
    stock: 9,
  },
  {
    id: 6,
    name: "Cotton Panjabi — XL",
    category: "Panjabi",
    brand: "Aarong",
    purchase: "870.00",
    selling: "1,490.00",
    stock: 15,
  },
];

export const DEFAULT_STOCK_ITEMS = [
  {
    id: 1,
    name: "SPT",
    lot: 1,
    discount: "no(0)",
    date: "05 Nov 2023",
    barcode: "",
    purchase: 0,
    sale: 250,
    stock: 996,
    alert: 0,
  },
  {
    id: 2,
    name: "SPT Camp Test",
    lot: 1,
    discount: "no(0)",
    date: "05 Nov 2023",
    barcode: "",
    purchase: 0,
    sale: 250,
    stock: 989,
    alert: 0,
  },
  {
    id: 3,
    name: "Matador i-teen Gel",
    lot: 1,
    discount: "no(0)",
    date: "01 Jan 1970",
    barcode: "0011",
    purchase: 8,
    sale: 10,
    stock: 199,
    alert: 2,
  },
  {
    id: 4,
    name: "Mens Snekers Shoes 103",
    variant: "(32)",
    lot: 2,
    discount: "no(0)",
    date: "24 Aug 2024",
    barcode: "",
    purchase: 200,
    sale: 250,
    stock: 5,
    alert: 0,
  },
  {
    id: 5,
    name: "Ayesha",
    lot: 4,
    discount: "no(0)",
    date: "04 Nov 2024",
    barcode: "",
    purchase: 160000,
    sale: 180000,
    stock: 100,
    alert: 0,
  },
  {
    id: 6,
    name: "Matador Eraser",
    lot: 1,
    discount: "no(0)",
    date: "01 Jan 1970",
    barcode: "5566",
    purchase: 5,
    sale: 10,
    stock: 114,
    alert: 2,
  },
  {
    id: 7,
    name: "Cotton Panjabi — L",
    lot: 1,
    discount: "10%",
    date: "12 Feb 2025",
    barcode: "8841",
    purchase: 850,
    sale: 1450,
    stock: 24,
    alert: 5,
  },
  {
    id: 8,
    name: "Denim Jeans — 32",
    lot: 2,
    discount: "no(0)",
    date: "03 Mar 2025",
    barcode: "9021",
    purchase: 1100,
    sale: 1890,
    stock: 4,
    alert: 3,
  },
];

export const DEFAULT_STOCK_ALERT_ITEMS = [
  { id: 1, name: "A4 Tech Keyboard", barcode: "8941193078563", alertQty: 1, currentStock: 0 },
  { id: 2, name: "sun flower doll", barcode: "3636593589", alertQty: 10, currentStock: 9 },
  { id: 3, name: "penguin medium", barcode: "3957520364", alertQty: 2, currentStock: 2 },
];

export const DEFAULT_CRM_PERMISSIONS = [
  { id: 1, name: "crm.lead.view" },
  { id: 2, name: "crm.lead.create" },
  { id: 3, name: "crm.follow.up.reminder" },
  { id: 4, name: "crm.customer.notes" },
  { id: 5, name: "crm.deal.pipeline" },
];

export const BRANCH_AVAILABLE_PERMISSIONS = [
  "branch.customer.take.payment",
  "branch.deliveryman",
  "branch.expense",
  "branch.income",
  "branch.opening.own",
  "branch.supplier",
  "create.product",
];

export const BRANCH_GRANTED_PERMISSIONS_DEFAULT = [
  "branch.customers",
  "branch.damage.product",
  "branch.dashboard",
  "branch.hide.stock.price",
  "branch.product.purchase.price",
  "branch.product.stock",
  "branch.received.customer.due",
  "branch.reports",
  "branch.return.product",
  "branch.sell",
  "branch.sell.discount",
  "branch.setting",
  "stock.transfer.b2b.b2g",
  "stock.transfer.g2b",
];

export const PERMISSION_WINGS = {
  Account_Wing: [
    "account.bank.and.cash",
    "account.capital",
    "account.customer.report",
    "account.dashboard",
    "account.expense",
    "account.income.statement",
    "account.indirect.income",
    "account.ledger.head",
    "account.list.of.group",
    "account.loan",
    "account.report",
    "account.statement",
    "account.transaction",
    "account.vouchers",
    "admin.transaction.vouchers",
  ],
  Godown_Wing: [
    "godown.dashboard",
    "godown.stock.in.out.report",
    "godown.stock.info",
    "godown.stock.out",
  ],
  Main_Wing: [
    "admin.branch.product.stock",
    "admin.crm",
    "admin.damage.product",
    "admin.dashboard",
  ],
  Supplier_Wing: [
    "supplier.dashboard",
    "supplier.due.report",
    "supplier.ledger",
    "supplier.payment",
  ],
};

export const DEMO_TRANSFER_STOCK = [
  {
    id: 1,
    name: "Sandwich Hot Spicy",
    brand: "Center Cafe",
    lot: 1,
    price: 120,
    discount: "no(0)",
    vat: "0%",
    stockUnit: 96,
    unitLabel: "pcs",
  },
  {
    id: 2,
    name: "Hot chickens Noodles",
    brand: "Samyang",
    lot: 2,
    price: 5200,
    discount: "no(0)",
    vat: "0%",
    stockUnit: 1,
    unitLabel: "Carton",
  },
  {
    id: 3,
    name: "Expiry date test",
    brand: "FARA IT",
    lot: 3,
    price: 115,
    discount: "no(0)",
    vat: "0%",
    stockUnit: 45,
    unitLabel: "pcs",
  },
  {
    id: 4,
    name: "Cotton Panjabi — L",
    brand: "Aarong",
    lot: 1,
    price: 1450,
    discount: "10%",
    vat: "0%",
    stockUnit: 24,
    unitLabel: "pcs",
  },
  {
    id: 5,
    name: "Denim Jeans — 32",
    brand: "Yellow",
    lot: 2,
    price: 1890,
    discount: "no(0)",
    vat: "0%",
    stockUnit: 4,
    unitLabel: "pcs",
  },
];

export const VARIATION_CHIP_COLORS = [
  COLORS.magenta,
  COLORS.peacock,
  COLORS.forest,
  COLORS.marigold,
  COLORS.purple,
  COLORS.rust,
];

export const PAGE_LABELS = {
  dashboard: "Main Wing Dashboard",
  settings: "Settings",
  tutorial: "Tutorial",
  permissions: "Admin Helper Roll & Permissions",
  "renew-service": "Renew Service",
  "renew-history": "Service Renew Histoy",
  "delivery-man": "Delivery man",
  branch: "Branch",
  "branch-role-permission": "Branch role & permission",
  crm: "CRM",
  "product-stocks": "Product Stocks",
  "product-summery": "Product Summery",
  "stock-alert-qty": "Stock Alert Quantity",
  "product-ledger": "Product Ledger Table",
  "add-new-product": "Add New Product",
  "all-products": "All Products",
  brands: "Brands",
  categories: "Categories",
  "unit-types": "Unit Types",
  "upload-product-csv": "Upload Product By CSV",
  "print-barcode-labels": "Print Barcode / Labels",
  variations: "Variations",
  "create-transfer-b2b": "Create Transfer[B2B, B2G]",
  "stock-transfer-g2b": "Stock Transfer[G2B]",
  "transfer-histories": "Transfered Histories",
};